activity:
  enabled: true
  weight: 1.2
  smoothing_window: 120
  process:
    Code: focus
    Obsidian: focus
    POWERPNT: focus
    Acrobat: focus
    DingTalk: focus
    Feishu: focus
    Wemeet: focus
    steam: chill
    explorer: chill
    chrome: chill
    firefox: chill
    cloudmusic: chill
    ui32: chill
    QQ: chill
    WindowsTerminal: focus
  title:
    GitHub: focus
    Stack Overflow: focus
    Docs: focus
    Jupyter: focus
    YouTube: chill
    直播: chill
  matchers: []
