import type { Locale, SceneId } from "@/api/profile"
import type { DisturbancePreset } from "@/setup/model"

const zh = {
  appName: "WEScheduler",
  mode: { setup: "首次设置", settings: "设置" },
  loading: { title: "正在读取设置", description: "连接本地调度器并准备 Profile 草稿。" },
  unavailable: {
    title: "无法连接到 WEScheduler",
    description: "请确认主程序仍在运行，然后重试。",
    retry: "重试",
  },
  steps: {
    wallpaper: { title: "Wallpaper Engine", short: "找到安装位置并读取播放列表" },
    weather: { title: "天气服务", short: "填写 OpenWeatherMap API Key" },
    location: { title: "所在地点", short: "设置用于天气判断的位置" },
    scenes: { title: "场景绑定", short: "把使用情境连接到播放列表" },
    scheduling: { title: "调度体验", short: "决定响应方式和打扰程度" },
    activity: { title: "Activity 检测", short: "识别工作与休闲活动" },
    review: { title: "检查并完成", short: "确认草稿并一次性保存" },
  },
  nav: {
    setupDescription: "完成必要设置后，调度器才会启动。",
    settingsDescription: "修改只保存在草稿中，保存后才会生效。",
    current: "当前",
    complete: "完成",
    optional: "可跳过",
  },
  common: {
    back: "返回",
    next: "继续",
    cancel: "取消",
    close: "关闭",
    retry: "重试",
    required: "必填",
    needsAttention: "需要处理",
    optional: "可选",
    notSet: "未设置",
    custom: "自定义",
    show: "显示",
    hide: "隐藏",
    remove: "移除",
  },
  wallpaper: {
    title: "连接 Wallpaper Engine",
    description: "先读取 Wallpaper Engine 的本地配置，后续场景只会绑定到实际存在的播放列表。",
    pathLabel: "Wallpaper Engine 可执行文件",
    pathDescription: "通常是 Steam 安装目录中的 wallpaper64.exe。留空时会尝试自动检测。",
    pathPlaceholder: "自动检测，或选择 wallpaper64.exe",
    choose: "选择文件",
    detect: "自动检测",
    scan: "扫描播放列表",
    scanning: "正在扫描",
    found: "已连接",
    foundDescription: (count: number) => `找到 ${count} 个可用播放列表。`,
    emptyTitle: "没有找到可用播放列表",
    emptyDescription: "请先在 Wallpaper Engine 中创建至少一个包含壁纸的播放列表，然后重新扫描。",
    zeroItem: "没有壁纸",
    scanAgain: "重新扫描",
    manualHint: "如果自动检测失败，请手动选择 wallpaper64.exe。",
  },
  weather: {
    title: "连接天气服务",
    description: "WEScheduler 使用 OpenWeatherMap 判断晴雨、日出和日落。Key 只保存在本机 Profile 中。",
    keyLabel: "OpenWeatherMap API Key",
    keyDescription: "请输入有效的 Current Weather API Key。保存天气设置时会进行一次联网校验。",
    keyPlaceholder: "粘贴 API Key",
    getKey: "获取 API Key",
    validationOnSubmit: "首次设置或修改天气信息时，保存前会验证 API Key 与地点；Key 仍只保存在本机 Profile 中。",
  },
  location: {
    title: "设置所在地点",
    setupDescription: "可以按公网 IP 粗略定位到城市，也可以直接填写。检测结果不会自动更新，并且仍可手工修正。",
    settingsDescription: "位置只用于天气请求。修改后可以在保存前验证。",
    detect: "自动定位城市",
    detecting: "正在定位",
    detectHint: "仅在点击时通过 ipapi.co 查询公网 IP 对应的城市级位置，不保存 IP。",
    detected: "已填入检测到的城市位置，请确认是否准确。",
    detectionUnavailable: "暂时无法自动定位。请手工填写城市和经纬度，或稍后重试。",
    nameLabel: "地点名称",
    namePlaceholder: "例如：上海",
    latitudeLabel: "纬度",
    longitudeLabel: "经度",
    latitudePlaceholder: "-90 到 90",
    longitudePlaceholder: "-180 到 180",
    invalidLatitude: "纬度必须在 -90 到 90 之间。",
    invalidLongitude: "经度必须在 -180 到 180 之间。",
  },
  scenes: {
    title: "绑定使用场景",
    description: "启用需要的内置场景，并为每个场景选择 Wallpaper Engine 播放列表。多个场景可以共用一个播放列表。",
    enabled: "启用",
    playlist: "播放列表",
    choosePlaylist: "选择播放列表",
    required: "至少启用并绑定一个场景。",
    unavailable: "请先返回并扫描到至少一个非空播放列表。",
    groups: { context: "日常情境", season: "季节氛围", weather: "天气氛围" },
  },
  preferences: {
    title: "调整调度体验",
    description: "响应风格决定什么信息更重要；打扰程度决定何时适合切换。",
    responseTitle: "响应风格",
    responseDescription: "从长期背景氛围到当前天气和活动，选择调度器更偏向哪一侧。",
    disturbanceTitle: "打扰程度",
    disturbanceDescription: "选择一个预设，或展开具体时间进行微调。",
    fineTune: "微调具体时间",
    startupGrace: "启动等待",
    idleBeforeSwitch: "空闲等待",
    maximumDeferral: "最长延后",
    cycleInterval: "轮换间隔",
    seconds: "秒",
    minutes: "分钟",
    nonNegative: "请输入不小于 0 的整数。",
  },
  activity: {
    title: "识别当前活动",
    description: "这一项可以跳过。匹配忽略大小写，进程名中的 .exe 后缀也会自动忽略。",
    workTitle: "工作",
    leisureTitle: "休闲",
    processLabel: "进程名",
    titleKeywordLabel: "窗口标题关键词",
    processPlaceholder: "输入进程名，按 Enter 添加",
    keywordPlaceholder: "输入关键词，按 Enter 添加",
    add: "添加",
    empty: "暂未添加",
    conflictTitle: "存在冲突规则",
    conflictDescription: (values: string) => `这些项目同时出现在工作和休闲中：${values}`,
  },
  review: {
    title: "检查后保存",
    description: "此前内容仍然只是草稿。确认后才会一次性写入 Profile。",
    wallpaper: "Wallpaper Engine",
    weather: "天气服务",
    location: "地点",
    scenes: "已启用场景",
    response: "响应风格",
    disturbance: "打扰程度",
    activity: "Activity 规则",
    apiKeySet: "API Key 已填写",
    sceneCount: (count: number) => `${count} 个场景`,
    activityCount: (count: number) => `${count} 条规则`,
    create: "完成设置",
    creating: "正在创建",
    save: "保存并应用",
    saving: "正在保存",
    success: "已保存并生效",
    setupSuccess: "设置已完成，正在启动调度器。",
  },
  errors: {
    validation: "请先完成当前页面的必填内容。",
    fieldValidation: "服务端发现了需要修改的字段，请按下方提示修正。",
    profileAlreadyExists: "Profile 已经存在。请关闭窗口后从托盘重新打开设置。",
    applyTimeout: "调度器暂时没有完成应用。草稿仍然保留，请重试。",
    applyUnavailable: "调度器当前不接受配置修改，请稍后重试。",
    weatherValidationUnavailable: "暂时无法连接 OpenWeatherMap 验证设置。草稿仍然保留，请稍后重试。",
    generic: "操作失败。草稿仍然保留，请重试。",
    scanCodes: {
      wallpaper_engine_executable_not_found: "没有找到 wallpaper64.exe。请手动选择安装位置。",
      wallpaper_engine_config_not_found: "没有找到 Wallpaper Engine config.json。请先启动一次 Wallpaper Engine，然后重试。",
      wallpaper_engine_config_read_failed: "Wallpaper Engine 配置暂时无法读取。请关闭可能正在写入配置的窗口后重试。",
      unexpected_wallpaper_engine_config_format: "Wallpaper Engine 配置格式无法识别。",
    },
    issueCodes: {
      weather_api_key_invalid: "OpenWeatherMap 拒绝了这个 API Key。新 Key 可能需要等待一段时间才会激活。",
      weather_location_invalid: "OpenWeatherMap 无法使用这个地点，请检查经纬度。",
      weather_api_quota_exceeded: "这个 API Key 当前已达到请求配额，请稍后重试或更换 Key。",
    },
    stages: { compile: "配置编译", prepare: "运行时准备", persist: "Profile 写入" },
  },
}

const en: typeof zh = {
  appName: "WEScheduler",
  mode: { setup: "First-time setup", settings: "Settings" },
  loading: { title: "Loading settings", description: "Connecting to the local scheduler and preparing a Profile draft." },
  unavailable: {
    title: "WEScheduler is unavailable",
    description: "Make sure the main application is still running, then try again.",
    retry: "Try again",
  },
  steps: {
    wallpaper: { title: "Wallpaper Engine", short: "Find the installation and read playlists" },
    weather: { title: "Weather service", short: "Enter an OpenWeatherMap API key" },
    location: { title: "Location", short: "Set the location used for weather" },
    scenes: { title: "Scene assignments", short: "Connect contexts to playlists" },
    scheduling: { title: "Scheduling feel", short: "Choose responsiveness and interruption" },
    activity: { title: "Activity detection", short: "Recognize work and leisure activity" },
    review: { title: "Review and finish", short: "Review the draft and save once" },
  },
  nav: {
    setupDescription: "The scheduler starts after the required setup is complete.",
    settingsDescription: "Changes stay in this draft until you save them.",
    current: "Current",
    complete: "Complete",
    optional: "Optional",
  },
  common: {
    back: "Back",
    next: "Continue",
    cancel: "Cancel",
    close: "Close",
    retry: "Retry",
    required: "Required",
    needsAttention: "Needs attention",
    optional: "Optional",
    notSet: "Not set",
    custom: "Custom",
    show: "Show",
    hide: "Hide",
    remove: "Remove",
  },
  wallpaper: {
    title: "Connect Wallpaper Engine",
    description: "Read Wallpaper Engine's local configuration first, so Scenes can only use playlists that actually exist.",
    pathLabel: "Wallpaper Engine executable",
    pathDescription: "Usually wallpaper64.exe inside the Steam installation. Leave blank to try automatic detection.",
    pathPlaceholder: "Auto-detect, or choose wallpaper64.exe",
    choose: "Choose file",
    detect: "Auto-detect",
    scan: "Scan playlists",
    scanning: "Scanning",
    found: "Connected",
    foundDescription: (count: number) => `Found ${count} usable playlists.`,
    emptyTitle: "No usable playlists found",
    emptyDescription: "Create at least one Wallpaper Engine playlist containing a wallpaper, then scan again.",
    zeroItem: "No wallpapers",
    scanAgain: "Scan again",
    manualHint: "If automatic detection fails, choose wallpaper64.exe manually.",
  },
  weather: {
    title: "Connect weather",
    description: "WEScheduler uses OpenWeatherMap for conditions, sunrise, and sunset. The key stays in the local Profile.",
    keyLabel: "OpenWeatherMap API key",
    keyDescription: "Enter a valid Current Weather API key. Weather changes are checked online before saving.",
    keyPlaceholder: "Paste API key",
    getKey: "Get an API key",
    validationOnSubmit: "First-time setup and weather changes validate the API key and location before saving. The key remains only in the local Profile.",
  },
  location: {
    title: "Set your location",
    setupDescription: "Estimate a city from your public IP, or enter the location directly. The result is not updated automatically and remains editable.",
    settingsDescription: "Location is used only for weather requests. Changes are validated before saving.",
    detect: "Detect my city",
    detecting: "Detecting",
    detectHint: "Only when clicked, ipapi.co estimates a city-level location from your public IP. The IP is not saved.",
    detected: "The detected city location was filled in. Confirm that it is accurate.",
    detectionUnavailable: "Automatic location is temporarily unavailable. Enter the city and coordinates manually, or try again later.",
    nameLabel: "Location name",
    namePlaceholder: "For example: Shanghai",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    latitudePlaceholder: "-90 to 90",
    longitudePlaceholder: "-180 to 180",
    invalidLatitude: "Latitude must be between -90 and 90.",
    invalidLongitude: "Longitude must be between -180 and 180.",
  },
  scenes: {
    title: "Assign Scenes",
    description: "Enable built-in Scenes and choose a Wallpaper Engine playlist for each. Multiple Scenes may share a playlist.",
    enabled: "Enabled",
    playlist: "Playlist",
    choosePlaylist: "Choose a playlist",
    required: "Enable and assign at least one Scene.",
    unavailable: "Go back and scan at least one non-empty playlist first.",
    groups: { context: "Everyday context", season: "Seasonal atmosphere", weather: "Weather atmosphere" },
  },
  preferences: {
    title: "Tune scheduling",
    description: "Response style sets what matters most. Interruption level controls when a switch is appropriate.",
    responseTitle: "Response style",
    responseDescription: "Choose whether long-term atmosphere or current weather and activity should carry more weight.",
    disturbanceTitle: "Interruption level",
    disturbanceDescription: "Choose a preset, or expand the exact timing values.",
    fineTune: "Fine-tune timing",
    startupGrace: "Startup wait",
    idleBeforeSwitch: "Idle wait",
    maximumDeferral: "Maximum deferral",
    cycleInterval: "Rotation interval",
    seconds: "seconds",
    minutes: "minutes",
    nonNegative: "Enter a non-negative whole number.",
  },
  activity: {
    title: "Recognize activity",
    description: "This step is optional. Matching ignores letter case and the .exe suffix in process names.",
    workTitle: "Work",
    leisureTitle: "Leisure",
    processLabel: "Process names",
    titleKeywordLabel: "Window title keywords",
    processPlaceholder: "Enter a process and press Enter",
    keywordPlaceholder: "Enter a keyword and press Enter",
    add: "Add",
    empty: "Nothing added",
    conflictTitle: "Conflicting rules",
    conflictDescription: (values: string) => `These items appear in both work and leisure: ${values}`,
  },
  review: {
    title: "Review and save",
    description: "Everything above is still a draft. Confirm once to write the Profile.",
    wallpaper: "Wallpaper Engine",
    weather: "Weather service",
    location: "Location",
    scenes: "Enabled Scenes",
    response: "Response style",
    disturbance: "Interruption level",
    activity: "Activity rules",
    apiKeySet: "API key entered",
    sceneCount: (count: number) => `${count} Scenes`,
    activityCount: (count: number) => `${count} rules`,
    create: "Finish setup",
    creating: "Creating",
    save: "Save and apply",
    saving: "Saving",
    success: "Saved and applied",
    setupSuccess: "Setup is complete. Starting the scheduler.",
  },
  errors: {
    validation: "Complete the required fields on this page first.",
    fieldValidation: "The server found fields that need changes. Follow the messages below.",
    profileAlreadyExists: "A Profile already exists. Close this window and reopen Settings from the tray.",
    applyTimeout: "The scheduler did not finish applying the change. Your draft is still here; try again.",
    applyUnavailable: "The scheduler is not accepting configuration changes right now. Try again shortly.",
    weatherValidationUnavailable: "OpenWeatherMap is temporarily unavailable for validation. Your draft is still here; try again later.",
    generic: "The operation failed. Your draft is still here; try again.",
    scanCodes: {
      wallpaper_engine_executable_not_found: "wallpaper64.exe was not found. Choose the installation manually.",
      wallpaper_engine_config_not_found: "Wallpaper Engine config.json was not found. Start Wallpaper Engine once, then try again.",
      wallpaper_engine_config_read_failed: "Wallpaper Engine configuration could not be read. Close anything writing it, then try again.",
      unexpected_wallpaper_engine_config_format: "The Wallpaper Engine configuration format was not recognized.",
    },
    issueCodes: {
      weather_api_key_invalid: "OpenWeatherMap rejected this API key. A new key may need some time before it becomes active.",
      weather_location_invalid: "OpenWeatherMap could not use this location. Check the coordinates.",
      weather_api_quota_exceeded: "This API key has reached its request quota. Try later or use another key.",
    },
    stages: { compile: "configuration compilation", prepare: "runtime preparation", persist: "Profile write" },
  },
}

export const COPY = { zh, en } satisfies Record<Locale, typeof zh>

export const SCENE_LABELS: Record<Locale, Record<SceneId, string>> = {
  zh: {
    day_work: "日间工作",
    day_leisure: "日间休闲",
    night_work: "夜间工作",
    night_leisure: "夜间休闲",
    spring: "春季",
    summer: "夏季",
    autumn: "秋季",
    winter: "冬季",
    sunset: "黄昏",
    rain: "雨天",
  },
  en: {
    day_work: "Day work",
    day_leisure: "Day leisure",
    night_work: "Night work",
    night_leisure: "Night leisure",
    spring: "Spring",
    summer: "Summer",
    autumn: "Autumn",
    winter: "Winter",
    sunset: "Sunset",
    rain: "Rain",
  },
}

export const RESPONSE_STYLE_LABELS: Record<Locale, Record<import("@/api/profile").ResponseStyle, string>> = {
  zh: {
    background: "背景优先",
    background_leaning: "偏向背景",
    balanced: "平衡",
    current_leaning: "偏向当前",
    current: "当前优先",
  },
  en: {
    background: "Background first",
    background_leaning: "Lean background",
    balanced: "Balanced",
    current_leaning: "Lean current",
    current: "Current first",
  },
}

export const DISTURBANCE_LABELS: Record<Locale, Record<DisturbancePreset, string>> = {
  zh: { eager: "积极", responsive: "灵敏", balanced: "平衡", quiet: "安静", minimal: "最少打扰" },
  en: { eager: "Eager", responsive: "Responsive", balanced: "Balanced", quiet: "Quiet", minimal: "Minimal" },
}
